{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    {{- include "sovd-webapp.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "sovd-webapp.backend.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    {{- include "sovd-webapp.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "sovd-webapp.frontend.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.vehicleConnector.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vehicleConnector.service.name }}
  labels:
    {{- include "sovd-webapp.vehicleConnector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vehicleConnector.service.type }}
  ports:
  - port: {{ .Values.vehicleConnector.service.port }}
    targetPort: {{ .Values.vehicleConnector.service.targetPort }}
    protocol: TCP
    name: grpc
  selector:
    {{- include "sovd-webapp.vehicleConnector.selectorLabels" . | nindent 4 }}
{{- end }}
